### ISSUE TITLE
New image tag for elasticsearch clients 7.x

### ISSUE THREAD

**Issue by rsicart** [monotek/fluentd-elasticsearch#11]
Hi @monotek 

Actually I send logs to an Elasticsearch server (7.17.4) that I don't manage.

This morning I wanted to use the latest image v4.1.0 (built after #10) because I need a recent version of `fluent-plugin-kubernetes_metadata_filter (2.11.1)`, but I get those errors:

```
The client is unable to verify that the server is Elasticsearch. Some functionality may not be compatible if the server is running an unsupported product.
2022-07-06 08:51:04 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Using Elasticsearch client 8.3.0 is not compatible for your Elasticsearch server. Please check your using elasticsearch gem version and Elasticsearch server."
```

From that error I understand that I should use an elasticsearch client 7.x (until the server is updated).

Could be possible to have an image tag which installs elasticsearch client 7.x along with fluent-plugin-kubernetes_metadata_filter 2.11.1? For example a new image tag 3.5?

Please let me know if it is possible

Thanks in advance!

**Comment by monotek** [comment]
I dont want to relase a downgrade so you would have to to fork, build and publish your own image...
